In [2]:
import cv2
import mediapipe as mp
mp_face_detection = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils

# For webcam input:
cap = cv2.VideoCapture(0)
with mp_face_detection.FaceDetection(
    model_selection=0, min_detection_confidence=0.5) as face_detection:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = face_detection.process(image)

    # Draw the face detection annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.detections:
      for detection in results.detections:
        mp_drawing.draw_detection(image, detection)
        print(detection)
        location_data = detection.location_data
        print(detection.location_data.relative_bounding_box)
        #print(detection.location_data.relative_bounding_box.xmin)
        normalized_x=detection.location_data.relative_bounding_box.xmin
        normalized_y=detection.location_data.relative_bounding_box.ymin
        normalized_w=detection.location_data.relative_bounding_box.width
        normalized_h=detection.location_data.relative_bounding_box.height
        
        x_px = min(math.floor(normalized_x * image_width), image_width - 1)
        y_px = min(math.floor(normalized_y * image_height), image_height - 1)
        w_px = min(math.floor(normalized_w * image_width), image_width - 1)
        h_px = min(math.floor(normalized_h * image_height), image_height - 1)
        print(x_px, y_px, w_px, h_px)
        
        
    # Flip the image horizontally for a selfie-view display.
    cv2.imshow('MediaPipe Face Detection', image)
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()
cv2.destroyAllWindows()

label_id: 0
score: 0.9412506222724915
location_data {
  format: RELATIVE_BOUNDING_BOX
  relative_bounding_box {
    xmin: 0.33953961730003357
    ymin: 0.47425389289855957
    width: 0.3054411709308624
    height: 0.4072263836860657
  }
  relative_keypoints {
    x: 0.4305371046066284
    y: 0.5684055685997009
  }
  relative_keypoints {
    x: 0.559201180934906
    y: 0.5666962265968323
  }
  relative_keypoints {
    x: 0.49759331345558167
    y: 0.648244321346283
  }
  relative_keypoints {
    x: 0.49555954337120056
    y: 0.7457733154296875
  }
  relative_keypoints {
    x: 0.3529866933822632
    y: 0.6349225640296936
  }
  relative_keypoints {
    x: 0.6265584230422974
    y: 0.6346601843833923
  }
}

xmin: 0.33953961730003357
ymin: 0.47425389289855957
width: 0.3054411709308624
height: 0.4072263836860657

0.33953961730003357
217 227 195 195
label_id: 0
score: 0.9372945427894592
location_data {
  format: RELATIVE_BOUNDING_BOX
  relative_bounding_box {
    xmin: 0.338018536567688
    

In [1]:
import math
import cv2
import mediapipe as mp

mp_face_detection = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils
cnt=1


cap = cv2.VideoCapture(0)
with mp_face_detection.FaceDetection(
    model_selection=0, min_detection_confidence=0.5) as face_detection:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = face_detection.process(image)

    # Draw the face detection annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image_width = image.shape[1]
    image_height = image.shape[0]
    if results.detections:
      for detection in results.detections:
        #print(detection)
        location_data = detection.location_data
        #print(detection.location_data.relative_bounding_box)
        #print(detection.location_data.relative_bounding_box.xmin)
        normalized_x=detection.location_data.relative_bounding_box.xmin
        normalized_y=detection.location_data.relative_bounding_box.ymin
        normalized_w=detection.location_data.relative_bounding_box.width
        normalized_h=detection.location_data.relative_bounding_box.height
        
        x_px = min(math.floor(normalized_x * image_width), image_width - 1)
        y_px = min(math.floor(normalized_y * image_height), image_height - 1)
        w_px = min(math.floor(normalized_w * image_width), image_width - 1)
        h_px = min(math.floor(normalized_h * image_height), image_height - 1)
        #print(x_px, y_px, w_px, h_px)
        
        #mp_drawing.draw_detection(image, detection)
    cv2.putText(image, str(cnt), (40,40),cv2.FONT_HERSHEY_COMPLEX,4,(0,0,255),2)
    # Flip the image horizontally for a selfie-view display.
    cv2.imshow('MediaPipe Face Detection', cv2.flip(image, 1))
    
    #관심 영역 추출
    roi = image[y_px:y_px+h_px, x_px:x_px+w_px]
    dst = cv2.resize(roi, dsize=(224, 224), interpolation=cv2.INTER_AREA)
    cv2.imshow("dst", cv2.flip(dst,1))
    
    #이미지 저장
    file_path="C:/Users/kkhhj/Desktop/face_recognize_data_mp/p1/" + str(cnt) + '.jpg'
    img_save= cv2.imwrite(file_path, dst)
            
    #1초 대기
    cv2.waitKey(1000)
    print(cnt)
    cnt += 1
    if cnt == 100:
        break
    
    if cv2.waitKey(5) & 0xFF == 27:
      break

cap.release()
cv2.destroyAllWindows()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [50]:
from google_images_download import google_images_download   

  #class instantiation
response = google_images_download.googleimagesdownload()   

  # keywords : 원하는 검색 키워드
  # limit : 원하는 다운로드 사진 개수 (수정 버전에서는 최대 100개까지 가능)
  # format : 다운로드 확장자 지정
arguments = {"keywords":"박찬호",
                          "limit":100,
                          "print_urls":True,
                          "format":"jpg"
                              }

  #passing the arguments to the function
paths = response.download(arguments)   

  #printing absolute paths of the downloaded images
print(paths)


Item no.: 1 --> Item name = \ubc15\ucc2c\ud638
Evaluating...
Starting Download...
Image URL: https://w.namu.la/s/91ecc2d3b3958b2c92e8706b1d3b9a12fdcd882b80b9ef1861c46e3918065a813320087f3bce2246cd93fc55b5e8d72f634b37251451bfa64c04286b2f330aa0725b750a2e3b52ec8742f327421e5a77
Completed Image ====> 1.91ecc2d3b3958b2c92e8706b1d3b9a12fdcd882b80b9ef1861c46e3918065a813320087f3bce2246cd93fc55b5e8d72f634b37251451bfa64c04286b2f330aa0725b750a2e3b52ec8742f327421e5a77.jpg
Image URL: http://www.anewsa.com/news_images/2019/07/03/mark/20190703164724.jpg
Completed Image ====> 2.20190703164724.jpg
Image URL: https://post-phinf.pstatic.net/MjAyMTAxMTNfMTI2/MDAxNjEwNTIzMDM0MzU2.2doMPH4L1wuZm9An07CT4u7NMtLkpap7dUowUeIeDwwg.29Dugauct2nQ6MfcRt0hB7pFj8dXGRPDijpJffWp4U0g.JPEG/images.jpg?type=w1200
Completed Image ====> 3.images.jpg
Image URL: https://ww.namu.la/s/6f3cdab0ab53fda233e963de166fd9de7781cb805cc7c4b9b434564beb66d158f9285eb664e22003777414463e82016f7e178494d4d78d75bf954bf36876b0af015dc81d6e85c58c400e2

In [6]:
import os
import cv2
import math
import mediapipe as mp

mp_face_detection = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils

# For static images:
IMAGE_FILES = []
tmt_dir = os.listdir("C:/Users/kkhhj/Desktop/tmt")

for i in tmt_dir:
    path = "C:/Users/kkhhj/Desktop/tmt/" + i
    IMAGE_FILES.append(path)

cnt=1
with mp_face_detection.FaceDetection(
    model_selection=1, min_detection_confidence=0.5) as face_detection:
  for idx, file in enumerate(IMAGE_FILES):
    image = cv2.imread(file)
    # Convert the BGR image to RGB and process it with MediaPipe Face Detection.
    results = face_detection.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    # Draw face detections of each face.
    if not results.detections:
      continue
    image_width = image.shape[1]
    image_height = image.shape[0]
    for detection in results.detections:
        normalized_x=detection.location_data.relative_bounding_box.xmin
        normalized_y=detection.location_data.relative_bounding_box.ymin
        normalized_w=detection.location_data.relative_bounding_box.width
        normalized_h=detection.location_data.relative_bounding_box.height
        
        x_px = min(math.floor(normalized_x * image_width), image_width - 1)
        y_px = min(math.floor(normalized_y * image_height), image_height - 1)
        w_px = min(math.floor(normalized_w * image_width), image_width - 1)
        h_px = min(math.floor(normalized_h * image_height), image_height - 1)
        print(x_px, y_px, w_px, h_px, cnt)
        cnt+=1
        
    # 관심 영역 추출    
    roi = image[y_px:y_px+h_px, x_px:x_px+w_px]
    if cnt==44:
        print(roi, file)
    dst = cv2.resize(roi, dsize=(224, 224), interpolation=cv2.INTER_AREA)
    cv2.imshow("dst", cv2.flip(dst,1))
        
    file_path="C:/Users/kkhhj/Desktop/face_recognize_data_mp/p2/" + str(idx) + '.jpg'
    cv2.imwrite(file_path, dst)


265 97 120 120 1
161 68 114 114 2
178 50 75 75 3
125 120 189 189 4
258 53 76 76 5
429 108 45 45 6
248 66 103 103 7
169 70 127 127 8
228 191 107 107 9
257 127 196 196 10
82 92 150 150 11
523 161 235 235 12
276 146 333 333 13
282 125 91 91 14
65 57 248 248 15
178 69 107 108 16
196 68 123 123 17
400 366 553 553 18
86 64 93 93 19
269 76 138 138 20
195 95 200 200 21
173 75 206 206 22
9 69 87 87 23
213 61 106 106 24
189 87 136 136 25
139 90 117 117 26
245 215 131 131 27
210 77 218 218 28
21 258 233 233 29
164 112 167 167 30
307 82 177 177 31
313 69 143 143 32
331 78 134 134 33
161 185 263 263 34
1267 384 368 368 35
638 113 155 155 36
319 53 82 82 37
66 127 157 157 38
233 36 87 87 39
236 130 168 168 40
174 41 549 549 41
182 50 118 118 42
119 27 196 196 43
[[[125 163 133]
  [125 161 131]
  [126 162 132]
  ...
  [ 62  27  14]
  [ 62  27  14]
  [ 62  27  14]]

 [[124 164 136]
  [122 160 132]
  [125 163 135]
  ...
  [ 65  27  15]
  [ 65  27  15]
  [ 63  28  15]]

 [[125 165 137]
  [125 163 135]
 

In [1]:
import os
import cv2
import numpy as np

model = cv2.face.LBPHFaceRecognizer_create()

faces=[]
ids=[]

dirs = os.listdir("C:/Users/kkhhj/Desktop/face_recognize_data_mp")
for dir_name in dirs:
    dir_path = "C:/Users/kkhhj/Desktop/face_recognize_data_mp/" + dir_name
    id_=int(dir_name[1])
    
    face_dir = os.listdir(dir_path)
    for i in face_dir:
        path = dir_path + "/" + i
        image = cv2.imread(path)
        image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        faces.append(image_gray)
        ids.append(id_)

from sklearn.utils import shuffle
X, y = shuffle(faces, ids, random_state=0)

model.train(X, np.array(y))
model.write("trained_model_mp.yml")
print("Finish training model !")

Finish training model !


In [1]:
import math
import cv2
import mediapipe as mp

face_recognizer = cv2.face.LBPHFaceRecognizer_create()
face_recognizer.read('trained_model_mp.yml')

names =["None", "minsol", "TMT"]

cap = cv2.VideoCapture(0)

mp_face_detection = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils

with mp_face_detection.FaceDetection(
    model_selection=0, min_detection_confidence=0.5) as face_detection:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = face_detection.process(image)

    # Draw the face detection annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image_width = image.shape[1]
    image_height = image.shape[0]
    if results.detections:
      for detection in results.detections:
        #print(detection)
        location_data = detection.location_data
        #print(detection.location_data.relative_bounding_box)
        #print(detection.location_data.relative_bounding_box.xmin)
        normalized_x=detection.location_data.relative_bounding_box.xmin
        normalized_y=detection.location_data.relative_bounding_box.ymin
        normalized_w=detection.location_data.relative_bounding_box.width
        normalized_h=detection.location_data.relative_bounding_box.height
        
        x_px = min(math.floor(normalized_x * image_width), image_width - 1)
        y_px = min(math.floor(normalized_y * image_height), image_height - 1)
        w_px = min(math.floor(normalized_w * image_width), image_width - 1)
        h_px = min(math.floor(normalized_h * image_height), image_height - 1)
        #print(x_px, y_px, w_px, h_px)
        
        #mp_drawing.draw_detection(image, detection)
    
    
    #관심 영역 추출
    cv2.rectangle(image, (x_px,y_px), (x_px+w_px, y_px+h_px), (255,0,0),3)
    roi = image[y_px:y_px+h_px, x_px:x_px+w_px]
    roi_gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    dst = cv2.resize(roi_gray, dsize=(224, 224), interpolation=cv2.INTER_AREA)
                
    id_, confidence = face_recognizer.predict(dst)
                
    if confidence < 60:
        name = names[id_]
        confidence = "  {0}%".format(round(100 - confidence))
        if id_ == 2:
            cv2.putText(image, "TMT IS", (20,150), cv2.FONT_HERSHEY_COMPLEX, 5, (0,0,255), 2)
            cv2.putText(image, "COMING..", (20,350), cv2.FONT_HERSHEY_COMPLEX, 5, (0,0,255), 2)
        
    else:
        name = "unknown"
        confidence = "  {0}%".format(round(100 - confidence))
                
    cv2.putText(image, str(name), (x_px+5,y_px-5), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
    #cv2.putText(image, str(confidence), (x_px+5,y_px+h_px-5), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 1) 
        
    # Flip the image horizontally for a selfie-view display.
    cv2.imshow('MediaPipe Face Detection', image)
    
    
    if cv2.waitKey(5) & 0xFF == 27:
      break

cap.release()
cv2.destroyAllWindows()
